import images from './images';
const memoriesData = [
    {
      id: 'moc-1',
        title: 'Bộ Ảnh của bạn DTTH dễ thương này :3',
        subtitle: 'NTT LOVE DTHH',
        date: '',
        description: 'Kỉ niệm 1 ngày đáng nhớ khi đi aeon mall với bạn của bạn DTTH :v',
      mediaItems: [
        { type: 'image', src: images.img1, alt: 'Ảnh' },
        { type: 'image', src: images.img2, alt: 'Ảnh' },
        { type: 'image', src: images.img3, alt: 'Ảnh' },
        { type: 'image', src: images.img4, alt: 'Ảnh' },
        { type: 'image', src: images.img5, alt: 'Ảnh' },
        { type: 'image', src: images.img6, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-2',
        title: 'Bộ Ảnh của bạn NTT không dễ thương nhưng max hài hước :v',
        subtitle: 'NTT LOVE DTHH',
        date: '',
        description: 'Kỉ niệm 1 ngày đáng nhớ khi cũng đi aeon mall với bạn của bạn NTT :v',
      mediaItems: [
        { type: 'image', src: images.img7, alt: 'Ảnh' },
        { type: 'image', src: images.img8, alt: 'Ảnh' },
        { type: 'image', src: images.img9, alt: 'Ảnh' },
        { type: 'image', src: images.img10, alt: 'Ảnh' },
        { type: 'image', src: images.img11, alt: 'Ảnh' },
        { type: 'image', src: images.img12, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-3',
        title: 'Lời chúc đáng yêu kỉ niệm 100 ngày của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '23/7/2020',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/oRS5hSw1eFM', alt: 'Video' },
      ],
    },
    {
      id: 'moc-4',
        title: 'Bộ ảnh Kỉ Niệm 100 Ngày Yêu Của Chúng Ta :3',
        subtitle: 'NTT LOVE DTHH',
        date: '23/7/2020',
        description: 'Lần đầu tiên đôi ta diện áo đôi :3',
      mediaItems: [
        { type: 'image', src: images.img13, alt: 'Ảnh' },
        { type: 'image', src: images.img14, alt: 'Ảnh' },
        { type: 'image', src: images.img15, alt: 'Ảnh' },
        { type: 'image', src: images.img16, alt: 'Ảnh' },
        { type: 'image', src: images.img17, alt: 'Ảnh' },
        { type: 'image', src: images.img18, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-5',
        title: 'Bộ ảnh Đi Cộng Cafe :v',
        subtitle: 'NTT LOVE DTHH',
        date: '18/8/2020',
        description: 'Hai đứa rảnh háng đi chọn chụp mấy chục cái app sửa ảnh :))',
      mediaItems: [
        { type: 'image', src: images.img19, alt: 'Ảnh' },
        { type: 'image', src: images.img20, alt: 'Ảnh' },
        { type: 'image', src: images.img21, alt: 'Ảnh' },
        { type: 'image', src: images.img22, alt: 'Ảnh' },
        { type: 'image', src: images.img23, alt: 'Ảnh' },
        { type: 'image', src: images.img24, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-6',
        title: 'Bộ ảnh Kỉ Niệm Đi Bát Tràng Cùng Nhau :3',
        subtitle: 'NTT LOVE DTHH',
        date: '27/9/2020',
        description: 'Lần đầu tiên đôi ta đi phượt :))',
      mediaItems: [
        { type: 'image', src: images.img25, alt: 'Ảnh' },
        { type: 'image', src: images.img26, alt: 'Ảnh' },
        { type: 'image', src: images.img27, alt: 'Ảnh' },
        { type: 'image', src: images.img28, alt: 'Ảnh' },
        { type: 'image', src: images.img29, alt: 'Ảnh' },
        { type: 'image', src: images.img30, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-7',
        title: 'Lời chúc zui zẻ kỉ niệm 200 ngày yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '31/10/2020',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/xrymEtd089w', alt: 'Video' },
      ],
    },
    {
      id: 'moc-8',
        title: 'Bộ ảnh Kỉ Niệm 200 Ngày Yêu Của Chúng Ta :3',
        subtitle: 'NTT LOVE DTHH',
        date: '31/10/2020',
        description: 'Lần đầu tiên đôi ta diện ốp đôi :))',
      mediaItems: [
        { type: 'image', src: images.img31, alt: 'Ảnh' },
        { type: 'image', src: images.img32, alt: 'Ảnh' },
        { type: 'image', src: images.img33, alt: 'Ảnh' },
        { type: 'image', src: images.img34, alt: 'Ảnh' },
        { type: 'image', src: images.img35, alt: 'Ảnh' },
        { type: 'image', src: images.img36, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-9',
        title: 'Bộ ảnh Kỉ Niệm Chuyến Đi Phượt Thứ 2 của Đôi Ta - Ba Vì 1 ngày toàn Mưa',
        subtitle: 'NTT LOVE DTHH',
        date: '15/11/2020',
        description: 'Lần thứ 2 đi phượt lại ướt sũng :))',
      mediaItems: [
        { type: 'image', src: images.img37, alt: 'Ảnh' },
        { type: 'image', src: images.img38, alt: 'Ảnh' },
        { type: 'image', src: images.img39, alt: 'Ảnh' },
        { type: 'image', src: images.img40, alt: 'Ảnh' },
        { type: 'image', src: images.img41, alt: 'Ảnh' },
        { type: 'image', src: images.img42, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-10',
        title: 'Bức ảnh Kỉ Niệm Lần đầu tiên Đôi ta đón năm mới cùng nhau',
        subtitle: 'NTT LOVE DTHH',
        date: '1/1/2021',
        description: 'Lần đầu tiên ngắm pháo hoa cùng nhau - Chụp được mỗi 1 bức này :))',
      mediaItems: [
        { type: 'image', src: images.img43, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-11',
        title: 'Lời chúc kỉ niệm 300 ngày yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '8/2/2021',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/xekIK_e13Ww', alt: 'Video' },
      ],
    },
    {
      id: 'moc-12',
        title: 'Bộ ảnh Kỉ Niệm Lần đi Cafe Lối Nhỏ - Không gian cực Chill',
        subtitle: 'NTT LOVE DTHH',
        date: '7/3/2021',
        description: 'Nhiều góc sống ảo quá nên lựa mới không hết :))',
      mediaItems: [
        { type: 'image', src: images.img44, alt: 'Ảnh' },
        { type: 'image', src: images.img45, alt: 'Ảnh' },
        { type: 'image', src: images.img46, alt: 'Ảnh' },
        { type: 'image', src: images.img47, alt: 'Ảnh' },
        { type: 'image', src: images.img48, alt: 'Ảnh' },
        { type: 'image', src: images.img49, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-13',
        title: 'Bộ ảnh Kỉ Niệm Lần Thứ 2 đi Highland Du Thuyền',
        subtitle: 'NTT LOVE DTHH',
        date: '24/3/2021',
        description: 'Lần thứ 2 lênh đênh trên mặt hồ :))',
      mediaItems: [
        { type: 'image', src: images.img50, alt: 'Ảnh' },
        { type: 'image', src: images.img51, alt: 'Ảnh' },
        { type: 'image', src: images.img52, alt: 'Ảnh' },
        { type: 'image', src: images.img53, alt: 'Ảnh' },
        
      ],
    },
    {
      id: 'moc-14',
        title: 'Lời chúc kỉ niệm 1 năm yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2021',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/JmUmJKCBilk', alt: 'Video' },
      ],
    },
    {
      id: 'moc-15',
        title: 'Bộ ảnh Kỉ Niệm 1 Năm Của Chúng Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2021',
        description: 'Lần đầu tiên đôi ta diện nhẫn đôi :3',
      mediaItems: [
        { type: 'image', src: images.img54, alt: 'Ảnh' },
        { type: 'image', src: images.img55, alt: 'Ảnh' },
        { type: 'image', src: images.img56, alt: 'Ảnh' },
        { type: 'image', src: images.img57, alt: 'Ảnh' },
        { type: 'image', src: images.img58, alt: 'Ảnh' },
        { type: 'image', src: images.img59, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-16',
        title: 'Bộ ảnh Kỉ Niệm Lần Thứ 3 Đi Phượt của Chúng Ta - Mai Châu Khung Cảnh Tuyệt Đẹp',
        subtitle: 'NTT LOVE DTHH',
        date: '1/5/2021',
        description: 'Lần đầu tiên đôi ta ấy ấy :v',
      mediaItems: [
        { type: 'image', src: images.img60, alt: 'Ảnh' },
        { type: 'image', src: images.img61, alt: 'Ảnh' },
        { type: 'image', src: images.img62, alt: 'Ảnh' },
        { type: 'image', src: images.img63, alt: 'Ảnh' },
        { type: 'image', src: images.img64, alt: 'Ảnh' },
        { type: 'image', src: images.img65, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-17',
        title: 'Lời chúc kỉ niệm 500 ngày yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '27/8/2021',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/Bq3b425Salo', alt: 'Video' },
      ],
    },
    {
      id: 'moc-18',
        title: 'Bộ ảnh Kỉ Niệm Sau 2 Tháng Trời Giãn Cách',
        subtitle: 'NTT LOVE DTHH',
        date: '17/10/2021',
        description: 'Lần đầu tiên đôi ta diện áo gió đôi :3',
      mediaItems: [
        { type: 'image', src: images.img66, alt: 'Ảnh' },
        { type: 'image', src: images.img67, alt: 'Ảnh' },
        { type: 'image', src: images.img68, alt: 'Ảnh' },
        { type: 'image', src: images.img69, alt: 'Ảnh' },
        { type: 'image', src: images.img70, alt: 'Ảnh' },
        { type: 'image', src: images.img71, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-19',
        title: 'Lời chúc kỉ niệm 20/10 và lời cổ vũ bảo vệ tốt nghiệp của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '20/10/2021',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/oKl4Hk0bLH8', alt: 'Video' },
      ],
    },
    {
      id: 'moc-20',
        title: 'Bộ ảnh Kỉ Niệm Em bảo vệ Tốt Nghiệp thành công',
        subtitle: 'NTT LOVE DTHH',
        date: '20/10/2021',
        description: 'Ngay sau khi em bảo vệ xong anh phi về đón em luôn :v',
      mediaItems: [
        { type: 'image', src: images.img72, alt: 'Ảnh' },
        { type: 'image', src: images.img73, alt: 'Ảnh' },
        { type: 'image', src: images.img74, alt: 'Ảnh' },
        { type: 'image', src: images.img75, alt: 'Ảnh' },
        { type: 'image', src: images.img76, alt: 'Ảnh' },
        { type: 'image', src: images.img77, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-21',
        title: 'Bộ ảnh Kỉ Niệm Đôi Ta đi cafe Urban',
        subtitle: 'NTT LOVE DTHH',
        date: '30/1/2022',
        description: 'Một ngày đẹp trời rảnh háng đi chill cafe :v',
      mediaItems: [
        { type: 'image', src: images.img78, alt: 'Ảnh' },
        { type: 'image', src: images.img79, alt: 'Ảnh' },
        { type: 'image', src: images.img80, alt: 'Ảnh' },
        { type: 'image', src: images.img81, alt: 'Ảnh' },
        { type: 'image', src: images.img82, alt: 'Ảnh' },
        { type: 'image', src: images.img83, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-22',
        title: 'Bộ ảnh Kỉ Niệm 2 Năm chúng ta yêu nhau :3',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2022',
        description: 'Anh yêu em nhất á :3',
      mediaItems: [
        { type: 'image', src: images.img84, alt: 'Ảnh' },
        { type: 'image', src: images.img85, alt: 'Ảnh' },
        { type: 'image', src: images.img86, alt: 'Ảnh' },
        { type: 'image', src: images.img87, alt: 'Ảnh' },
        { type: 'image', src: images.img88, alt: 'Ảnh' },
        { type: 'image', src: images.img89, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-23',
        title: 'Bức ảnh Kỉ Niệm Lễ tốt nghiệp của em',
        subtitle: 'NTT LOVE DTHH',
        date: '24/4/2022',
        description: 'Sau đó chúng ta ấy rất nhiều :))',
      mediaItems: [
        { type: 'image', src: images.img90, alt: 'Ảnh' },
        
      ],
    },
    {
      id: 'moc-24',
        title: 'Bộ ảnh Kỉ Niệm Lễ tốt nghiệp của anh',
        subtitle: 'NTT LOVE DTHH',
        date: '30/6/2022',
        description: 'Lễ tốt nghiệp ai ảnh người đó đẹp á :v',
      mediaItems: [
        { type: 'image', src: images.img91, alt: 'Ảnh' },
        { type: 'image', src: images.img92, alt: 'Ảnh' },
        { type: 'image', src: images.img93, alt: 'Ảnh' },
        { type: 'image', src: images.img94, alt: 'Ảnh' },
        { type: 'image', src: images.img95, alt: 'Ảnh' },
        { type: 'image', src: images.img96, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-25',
        title: 'Bộ ảnh Kỉ Niệm Ninh Bình 2022',
        subtitle: 'NTT LOVE DTHH',
        date: '30/10/2022',
        description: 'Đêm đó cũng tuyệt vời lắm :3',
      mediaItems: [
        { type: 'image', src: images.img97, alt: 'Ảnh' },
        { type: 'image', src: images.img98, alt: 'Ảnh' },
        { type: 'image', src: images.img99, alt: 'Ảnh' },
        { type: 'image', src: images.img100, alt: 'Ảnh' },
        { type: 'image', src: images.img101, alt: 'Ảnh' },
        { type: 'image', src: images.img102, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-26',
        title: 'Bức ảnh Kỉ Niệm noel 2022',
        subtitle: 'NTT LOVE DTHH',
        date: '24/12/2022',
        description: 'Cùng nhau đi dạo phố và làm ông già noel :3',
      mediaItems: [
        { type: 'image', src: images.img103, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-27',
        title: 'Bộ ảnh Kỉ Niệm Tam Đảo 2023',
        subtitle: 'NTT LOVE DTHH',
        date: '4/3/2023',
        description: 'Lễ tốt nghiệp ai ảnh người đó đẹp á :v',
      mediaItems: [
        { type: 'image', src: images.img104, alt: 'Ảnh' },
        { type: 'image', src: images.img105, alt: 'Ảnh' },
        { type: 'image', src: images.img106, alt: 'Ảnh' },
        { type: 'image', src: images.img107, alt: 'Ảnh' },
        { type: 'image', src: images.img108, alt: 'Ảnh' },
        { type: 'image', src: images.img109, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-28',
        title: 'Bộ ảnh của Tobby',
        subtitle: 'NTT LOVE DTHH',
        date: '1/4/2023',
        description: 'Đứa con dễ thương, ngờ nghệch và ngổ ngáo mà chúng ta yêu thương :v',
      mediaItems: [
        { type: 'image', src: images.img110, alt: 'Ảnh' },
        { type: 'image', src: images.img111, alt: 'Ảnh' },
        { type: 'image', src: images.img112, alt: 'Ảnh' },
        { type: 'image', src: images.img113, alt: 'Ảnh' },
        { type: 'image', src: images.img114, alt: 'Ảnh' },
        { type: 'image', src: images.img115, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-29',
        title: 'Lời chúc kỉ niệm 3 năm tình yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2023',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/DTQ96-EOCcg', alt: 'Video' },
      ],
    },
    {
      id: 'moc-30',
        title: 'Bộ ảnh Kỉ Niệm Hạ Long 2023',
        subtitle: 'NTT LOVE DTHH',
        date: '12/5/2023',
        description: 'Một chuyến đi đáng nhớ có vui, có buồn, có cả những cảm xúc mãnh liệt mà ta trao nhau!',
      mediaItems: [
        { type: 'image', src: images.img116, alt: 'Ảnh' },
        { type: 'image', src: images.img117, alt: 'Ảnh' },
        { type: 'image', src: images.img118, alt: 'Ảnh' },
        { type: 'image', src: images.img119, alt: 'Ảnh' },
        { type: 'image', src: images.img120, alt: 'Ảnh' },
        { type: 'image', src: images.img121, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-31',
        title: 'Bức ảnh Cosplay hồi xuân sinh viên của 2 đứa :v',
        subtitle: 'NTT LOVE DTHH',
        date: '12/9/2023',
        description: 'Sinh viên năm 8 UET và năm 6 NEU :v',
      mediaItems: [
        { type: 'image', src: images.img122, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-32',
        title: 'Bộ ảnh Kỉ Niệm Hải Phòng 2023',
        subtitle: 'NTT LOVE DTHH',
        date: '23/12/2023',
        description: 'Nhiều đồ ăn ngon và cả em cũng ngon :v',
      mediaItems: [
        { type: 'image', src: images.img123, alt: 'Ảnh' },
        { type: 'image', src: images.img124, alt: 'Ảnh' },
        { type: 'image', src: images.img125, alt: 'Ảnh' },
        { type: 'image', src: images.img126, alt: 'Ảnh' },
        { type: 'image', src: images.img127, alt: 'Ảnh' },
        { type: 'image', src: images.img128, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-33',
        title: 'Bộ ảnh Tobby part 2',
        subtitle: 'NTT LOVE DTHH',
        date: '14/3/2024',
        description: 'Vẫn là nó và những bức ảnh ngốc ngếch :v',
      mediaItems: [
        { type: 'image', src: images.img129, alt: 'Ảnh' },
        { type: 'image', src: images.img130, alt: 'Ảnh' },
        { type: 'image', src: images.img131, alt: 'Ảnh' },
        { type: 'image', src: images.img132, alt: 'Ảnh' },
        { type: 'image', src: images.img133, alt: 'Ảnh' },
        { type: 'image', src: images.img134, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-34',
        title: 'Bộ ảnh Những Lời chúc và món quà sinh nhật của Em dành cho Anh',
        subtitle: 'NTT LOVE DTHH',
        date: '6/4/2024',
        description: 'Kỉ niệm 4 năm bên nhau và 3 lần sinh nhật anh đều giữ đủ cả :3',
      mediaItems: [
        { type: 'image', src: images.img135, alt: 'Ảnh' },
        { type: 'image', src: images.img136, alt: 'Ảnh' },
        { type: 'image', src: images.img137, alt: 'Ảnh' },
        { type: 'image', src: images.img138, alt: 'Ảnh' },
        { type: 'image', src: images.img139, alt: 'Ảnh' },
        { type: 'image', src: images.img140, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-35',
        title: 'Lời chúc kỉ niệm 4 năm tình yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2024',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/J52CDSqXHII', alt: 'Video' },
      ],
    },
    {
      id: 'moc-36',
        title: 'Bộ ảnh Kỉ Niệm 4 Năm',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2024',
        description: 'Những món ăn ngon, bức ảnh đẹp và lần đầu đi đu idol cùng nhau :v',
      mediaItems: [
        { type: 'image', src: images.img141, alt: 'Ảnh' },
        { type: 'image', src: images.img142, alt: 'Ảnh' },
        { type: 'image', src: images.img143, alt: 'Ảnh' },
        { type: 'image', src: images.img144, alt: 'Ảnh' },
        { type: 'image', src: images.img145, alt: 'Ảnh' },
        { type: 'image', src: images.img146, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-37',
        title: 'Bộ ảnh Kỉ Niệm Lễ Dạm Ngõ Của Chúng Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '18/5/2024',
        description: 'Kỉ niệm lễ đầu chính thức của 2 bên gia đình chúng ta',
      mediaItems: [
        { type: 'image', src: images.img147, alt: 'Ảnh' },
        { type: 'image', src: images.img148, alt: 'Ảnh' },
        { type: 'image', src: images.img149, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-38',
        title: 'Lời chúc kỉ niệm 1500 ngày yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '23/5/2024',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/TbNg4qPsaUg', alt: 'Video' },
      ],
    },
    {
      id: 'moc-39',
        title: 'Bộ ảnh Kỉ Niệm 1500 Ngày Yêu',
        subtitle: 'NTT LOVE DTHH',
        date: '23/5/2024',
        description: 'Quán nướng ngon nhưng em còn ngon hơn tất cả :v',
      mediaItems: [
        { type: 'image', src: images.img150, alt: 'Ảnh' },
        { type: 'image', src: images.img151, alt: 'Ảnh' },
        { type: 'image', src: images.img152, alt: 'Ảnh' },
        { type: 'image', src: images.img153, alt: 'Ảnh' },
        { type: 'image', src: images.img154, alt: 'Ảnh' },
        { type: 'image', src: images.img155, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-40',
        title: 'Bức Ảnh Kỉ Niệm Ngày Cầu Hôn Em Của Anh',
        subtitle: 'NTT LOVE DTHH',
        date: '9/9/2024',
        description: '1 ngày đặc biệt chỉ đôi ta biết và diễn ra trong 1 hoàn cảnh cực kì đặc biệt mà cũng chỉ đôi ta biết!',
      mediaItems: [
        { type: 'image', src: images.img156, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-41',
        title: 'Bộ ảnh Cưới Của Đôi Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '7/10/2024',
        description: 'Ngày đôi ta đẹp nhất!',
      mediaItems: [
        { type: 'image', src: images.img157, alt: 'Ảnh' },
        { type: 'image', src: images.img158, alt: 'Ảnh' },
        { type: 'image', src: images.img159, alt: 'Ảnh' },
        { type: 'image', src: images.img160, alt: 'Ảnh' },
        { type: 'image', src: images.img161, alt: 'Ảnh' },
        { type: 'image', src: images.img162, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-42',
        title: 'Video Ảnh Cưới Của Chúng Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '17/10/2024',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://drive.google.com/file/d/1n3i2JYwCTkBnu8rR4bJncykY0gJqw22t/preview', alt: 'Video' },
      ],
    },
    {
      id: 'moc-43',
        title: 'Bộ ảnh ngày ăn Hỏi và Cưới Của Đôi Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '2/11/2024',
        description: 'Ngày trọng đại nhất của đôi ta',
      mediaItems: [
        { type: 'image', src: images.img163, alt: 'Ảnh' },
        { type: 'image', src: images.img164, alt: 'Ảnh' },
        { type: 'image', src: images.img165, alt: 'Ảnh' },
        { type: 'image', src: images.img166, alt: 'Ảnh' },
        { type: 'image', src: images.img167, alt: 'Ảnh' },
        { type: 'image', src: images.img168, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-44',
        title: 'Video Ngày Ăn Hỏi Và Ăn Cưới Của Đôi Ta',
        subtitle: 'NTT LOVE DTHH',
        date: '2/11/2024',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/acQSYOTx5Fg', alt: 'Video' },
      ],
    },
    {
      id: 'moc-45',
        title: 'Bức ảnh Kỉ Niệm Đi Ăn Cưới Phạm Thu Hà - Bạn thân của em',
        subtitle: 'NTT LOVE DTHH',
        date: '8/12/2024',
        description: 'Diện đồ đôi mới luôn nha :3',
      mediaItems: [
        { type: 'image', src: images.img169, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-46',
        title: 'Bộ ảnh Kỉ Niệm Giáng Sinh 2024',
        subtitle: 'NTT LOVE DTHH',
        date: '24/12/2024',
        description: 'Đi ăn, đi chơi và đi cafe',
      mediaItems: [
        { type: 'image', src: images.img170, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-47',
        title: 'Video Đón Năm Mới 2025 Cùng Nhau!',
        subtitle: 'NTT LOVE DTHH',
        date: '1/1/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/09_9lOOYX3g', alt: 'Video' },
      ],
    },
    {
      id: 'moc-48',
        title: 'Lời chúc Valentine 2025 của Anh!',
        subtitle: 'NTT LOVE DTHH',
        date: '14/2/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/QXC11gRqFtw', alt: 'Video' },
      ],
    },
    {
      id: 'moc-49',
        title: 'Bộ ảnh Kỉ Niệm Valentine 2025',
        subtitle: 'NTT LOVE DTHH',
        date: '14/2/2025',
        description: 'Dù vội vàng nhưng cái kết vẫn viên mãn :3',
      mediaItems: [
        { type: 'image', src: images.img171, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-50',
        title: 'Bộ ảnh kỉ niệm ngày sinh nhật 27 tuổi của anh',
        subtitle: 'NTT LOVE DTHH',
        date: '20/2/2025',
        description: 'Nhờ các bạn chụp cho đôi ta những bức ảnh đẹp này :3',
      mediaItems: [
        { type: 'image', src: images.img172, alt: 'Ảnh' },
        { type: 'image', src: images.img173, alt: 'Ảnh' },
        { type: 'image', src: images.img174, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-51',
        title: 'Bộ ảnh kỉ niệm Honeymoon - Đà Lạt 2025 của chúng ta',
        subtitle: 'NTT LOVE DTHH',
        date: '26/2/2025',
        description: '4 ngày 4 đêm với Đà Lạt mộng mơ, về rồi lại nhớ!',
      mediaItems: [
        { type: 'image', src: images.img175, alt: 'Ảnh' },
        { type: 'image', src: images.img176, alt: 'Ảnh' },
        { type: 'image', src: images.img177, alt: 'Ảnh' },
        { type: 'image', src: images.img178, alt: 'Ảnh' },
        { type: 'image', src: images.img179, alt: 'Ảnh' },
        { type: 'image', src: images.img180, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-52',
        title: 'Video Chuyến đi Honeymoon - Đà Lạt 2025 của chúng ta',
        subtitle: 'NTT LOVE DTHH',
        date: '26/2/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
        mediaItems: [
          { 
            type: 'video', 
            src: 'https://drive.google.com/file/d/11AX83ZIqUerGXymvMSEMMpC_n8vXEuQt/preview', 
            alt: 'Video',
            aspect: 'vertical'  // <-- Thêm thuộc tính này
          },
        ],
    },
    {
      id: 'moc-53',
        title: 'Bộ ảnh kỉ niệm 8/3 và ngày sinh nhật 25 tuổi của em',
        subtitle: 'NTT LOVE DTHH',
        date: '5/3/2025',
        description: 'Em và hoa đều xinh cả!',
      mediaItems: [
        { type: 'image', src: images.img181, alt: 'Ảnh' },
        { type: 'image', src: images.img182, alt: 'Ảnh' },
        { type: 'image', src: images.img183, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-54',
        title: 'Hát Mừng Sinh Nhật Tuổi 25 Của Em',
        subtitle: 'NTT LOVE DTHH',
        date: '5/3/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/zYA6z4U_0MM', alt: 'Video' },
      ],
    },
    {
      id: 'moc-55',
        title: 'Vlog Tour Đêm Hà Nội 2025',
        subtitle: 'NTT LOVE DTHH',
        date: '4/4/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
        mediaItems: [
          { 
            type: 'video', 
            src: 'https://drive.google.com/file/d/1nt9mTKGE2Y_SIGojfqkx-pbfNeUTLNzv/preview', 
            alt: 'Video',
            aspect: 'vertical'  // <-- Thêm thuộc tính này
          },
        ],
    },
    {
      id: 'moc-56',
        title: 'Bộ ảnh Tobby part 3',
        subtitle: 'NTT LOVE DTHH',
        date: '8/4/2025',
        description: 'Những khoảnh khắc của Tobby bên bố và mẹ cùng căn nhà cũ nhưng mà tầng mới:v',
      mediaItems: [
        { type: 'image', src: images.img184, alt: 'Ảnh' },
        { type: 'image', src: images.img185, alt: 'Ảnh' },
        { type: 'image', src: images.img186, alt: 'Ảnh' },
        { type: 'image', src: images.img187, alt: 'Ảnh' },
        { type: 'image', src: images.img188, alt: 'Ảnh' },
        { type: 'image', src: images.img189, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-57',
        title: 'Lời chúc kỉ niệm 5 năm tình yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/l4WasIx7B1Q', alt: 'Video' },
      ],
    },
    {
      id: 'moc-58',
        title: 'Bộ ảnh kỉ niệm 5 năm - yamada sushi',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2025',
        description: 'Bữa ăn thật ngon và những tấm ảnh đôi ta thật đẹp!',
      mediaItems: [
        { type: 'image', src: images.img190, alt: 'Ảnh' },
        { type: 'image', src: images.img191, alt: 'Ảnh' },
        { type: 'image', src: images.img192, alt: 'Ảnh' },
        { type: 'image', src: images.img193, alt: 'Ảnh' },
        { type: 'image', src: images.img194, alt: 'Ảnh' },
        { type: 'image', src: images.img195, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-59',
        title: 'Bộ ảnh kỉ niệm 5 năm - lối nhỏ kafe',
        subtitle: 'NTT LOVE DTHH',
        date: '14/4/2025',
        description: 'Một lần nữa lại là nơi đây, cơ sở khác nhưng vẫn có ảnh đẹp :v',
      mediaItems: [
        { type: 'image', src: images.img196, alt: 'Ảnh' },
        { type: 'image', src: images.img197, alt: 'Ảnh' },
        { type: 'image', src: images.img198, alt: 'Ảnh' },
        { type: 'image', src: images.img199, alt: 'Ảnh' },
        { type: 'image', src: images.img200, alt: 'Ảnh' },
        { type: 'image', src: images.img201, alt: 'Ảnh' },
        { type: 'image', src: images.img202, alt: 'Ảnh' },
        { type: 'image', src: images.img203, alt: 'Ảnh' },
        { type: 'image', src: images.img204, alt: 'Ảnh' },
        { type: 'image', src: images.img205, alt: 'Ảnh' },
        { type: 'image', src: images.img206, alt: 'Ảnh' },
        { type: 'image', src: images.img207, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-60',
        title: 'Bộ ảnh kỉ niệm Tour Đà Nẵng - Hội An - Bà Nà Hills - Huế 2025',
        subtitle: 'NTT LOVE DTHH',
        date: '3/7/2025',
        description: 'Chuyến đi lần đầu tiên vói gia đình nhà nội vui vẻ và đáng nhớ!',
      mediaItems: [
        { type: 'image', src: images.img208, alt: 'Ảnh' },
        { type: 'image', src: images.img209, alt: 'Ảnh' },
        { type: 'image', src: images.img210, alt: 'Ảnh' },
        { type: 'image', src: images.img211, alt: 'Ảnh' },
        { type: 'image', src: images.img212, alt: 'Ảnh' },
        { type: 'image', src: images.img213, alt: 'Ảnh' },
        { type: 'image', src: images.img214, alt: 'Ảnh' },
        { type: 'image', src: images.img215, alt: 'Ảnh' },
        { type: 'image', src: images.img216, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-61',
        title: 'Bộ ảnh kỉ niệm Cafe Sách Wiselands',
        subtitle: 'NTT LOVE DTHH',
        date: '18/7/2025',
        description: 'Trông sách và quán cafe này đẹp quá nên chúng ta lại có thêm ảnh đẹp :v',
      mediaItems: [
        { type: 'image', src: images.img217, alt: 'Ảnh' },
        { type: 'image', src: images.img218, alt: 'Ảnh' },
        { type: 'image', src: images.img219, alt: 'Ảnh' },
        { type: 'image', src: images.img220, alt: 'Ảnh' },
        { type: 'image', src: images.img221, alt: 'Ảnh' },
        { type: 'image', src: images.img222, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-62',
        title: 'Bộ ảnh kỉ niệm đi xem Sơ duyệt diễu binh',
        subtitle: 'NTT LOVE DTHH',
        date: '27/8/2025',
        description: 'Do quá đông nên chỉ có thể đứng xa xa chụp ảnh thôi, cũng may còn chỗ trên quán cafe :v',
      mediaItems: [
        { type: 'image', src: images.img223, alt: 'Ảnh' },
        { type: 'image', src: images.img224, alt: 'Ảnh' },
        { type: 'image', src: images.img225, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-63',
        title: 'Bộ ảnh kỉ niệm Đi xem triển lãm 80 năm thành tựu đất nước ',
        subtitle: 'NTT LOVE DTHH',
        date: '31/8/2025',
        description: 'Một pha tắc đường kinh điển để có thể đến được triển lãm tham quan và chụp được những bức ảnh kỉ niệm có bút chì và xe tăng :v',
      mediaItems: [
        { type: 'image', src: images.img226, alt: 'Ảnh' },
        { type: 'image', src: images.img227, alt: 'Ảnh' },
        { type: 'image', src: images.img228, alt: 'Ảnh' },
        { type: 'image', src: images.img229, alt: 'Ảnh' },
        { type: 'image', src: images.img230, alt: 'Ảnh' },
        { type: 'image', src: images.img231, alt: 'Ảnh' },
        { type: 'image', src: images.img232, alt: 'Ảnh' },
        { type: 'image', src: images.img233, alt: 'Ảnh' },
        { type: 'image', src: images.img234, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-64',
        title: 'Bộ ảnh kỉ niệm đi xem Diễu binh kỷ niệm 80 năm Quốc khánh Việt Nam',
        subtitle: 'NTT LOVE DTHH',
        date: '2/9/2025',
        description: 'Ngắm được đội xe bánh lốp mà không phải chen chúc, cũng gọi là có không khí :v',
      mediaItems: [
        { type: 'image', src: images.img235, alt: 'Ảnh' },
        { type: 'image', src: images.img236, alt: 'Ảnh' },
        { type: 'image', src: images.img237, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-65',
        title: 'Lời chúc kỉ niệm 2000 ngày yêu của anh dành cho NIKI :3',
        subtitle: 'NTT LOVE DTHH',
        date: '5/10/2025',
        description: 'Hãy xem và cảm nhận tình yêu anh dành cho em nhé !!!',
      mediaItems: [
        { type: 'video', src: 'https://www.youtube.com/embed/Jh4tN3ub7YI', alt: 'Video' },
      ],
    },
    {
      id: 'moc-66',
        title: 'Bộ ảnh kỉ niệm 2000 ngày - stirling steaks',
        subtitle: 'NTT LOVE DTHH',
        date: '5/10/2025',
        description: 'Quán decor đẹp, đồ ăn ngon và ảnh đôi ta cũng đẹp!',
      mediaItems: [
        { type: 'image', src: images.img238, alt: 'Ảnh' },
        { type: 'image', src: images.img239, alt: 'Ảnh' },
        { type: 'image', src: images.img240, alt: 'Ảnh' },
        { type: 'image', src: images.img241, alt: 'Ảnh' },
        { type: 'image', src: images.img242, alt: 'Ảnh' },
        { type: 'image', src: images.img243, alt: 'Ảnh' },
        { type: 'image', src: images.img244, alt: 'Ảnh' },
        { type: 'image', src: images.img245, alt: 'Ảnh' },
        { type: 'image', src: images.img246, alt: 'Ảnh' },
      ],
    },
    {
      id: 'moc-67',
        title: 'Bộ ảnh kỉ niệm 2000 ngày - Phố bích hoạ, hàng mã, tào phớ jelly bean và cafe phim',
        subtitle: 'NTT LOVE DTHH',
        date: '5/10/2025',
        description: 'Gợi nhắc lại kỉ niệm ngày đầu tiên đôi ta gặp nhau ngoài đời!',
      mediaItems: [
        { type: 'image', src: images.img247, alt: 'Ảnh' },
        { type: 'image', src: images.img248, alt: 'Ảnh' },
        { type: 'image', src: images.img249, alt: 'Ảnh' },
        { type: 'image', src: images.img250, alt: 'Ảnh' },
        { type: 'image', src: images.img251, alt: 'Ảnh' },
        { type: 'image', src: images.img252, alt: 'Ảnh' },
        { type: 'image', src: images.img253, alt: 'Ảnh' },
        { type: 'image', src: images.img254, alt: 'Ảnh' },
        { type: 'image', src: images.img255, alt: 'Ảnh' },
      ],
    },
    // Các mốc khác...
  ];
  
  export default memoriesData;
